name: PHPStan

on:
    push:
      branches: [ "master", "dfg-viewer-6.x", "dfg-viewer-6.x-ocr", "presentation-v4.x" ]
    pull_request:
      branches: [ "master" ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Codespell with annotations
        uses: codespell-project/actions-codespell@v2.0
        with:
            skip: "volumes,typo3ContentElementData.json"
            ignore_words_list: searchIn